name: Publish NuGet package

on:
  push:
    branches: [ master ]

jobs:
  create_and_publish_package:

    runs-on: windows-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Pack
      run: dotnet pack src -c Release -o tmp
      
    - name: Publish
      run: dotnet nuget push tmp/**/*.nupkg -s https://api.nuget.org/v3/index.json -k ${{ secrets.nuget_api_key }}
      
